flutter:
  uses-material-design: true
  assets:
    # Linux x64 binaries
    - assets/native/linux/x64/hello_c
    - assets/native/linux/x64/hello_cpp
    - assets/native/linux/x64/hello_rust
    - assets/native/linux/x64/hello_go
    
    # Linux ARM64 binaries
    - assets/native/linux/arm64/hello_c
    - assets/native/linux/arm64/hello_cpp
    - assets/native/linux/arm64/hello_rust
    - assets/native/linux/arm64/hello_go
    
    # Windows x64 binaries
    - assets/native/windows/x64/hello_c.exe
    - assets/native/windows/x64/hello_cpp.exe
    - assets/native/windows/x64/hello_rust.exe
    - assets/native/windows/x64/hello_go.exe
    
    # macOS x64 binaries
    - assets/native/macos/x64/hello_c
    - assets/native/macos/x64/hello_cpp
    - assets/native/macos/x64/hello_rust
    - assets/native/macos/x64/hello_go
